(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.tchajed.marshal.
Require Export New.golang.theory.
Require Export New.code.github_com.iasakura.perennial_sandbox.codec.

Set Default Proof Using "Type".

Module codec.
Module Pair.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : codec.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Pair_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (codec.Pair.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "A" ∷ l.[(codec.Pair.t), "A"] ↦{dq} v.(codec.Pair.A') ∗
      "B" ∷ l.[(codec.Pair.t), "B"] ↦{dq} v.(codec.Pair.B') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Pair_into_val_typed
   :
  IntoValTypedUnderlying (codec.Pair.t) (codec.Pairⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Pair_access_load_A l (v : (codec.Pair.t)) dq :
  AccessStrict
    (l.[(codec.Pair.t), "A"] ↦{dq} (v.(codec.Pair.A')))
    (l.[(codec.Pair.t), "A"] ↦{dq} (v.(codec.Pair.A')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Pair_access_store_A l (v : (codec.Pair.t)) A' :
  AccessStrict
    (l.[(codec.Pair.t), "A"] ↦ (v.(codec.Pair.A')))
    (l.[(codec.Pair.t), "A"] ↦ A')
    (l ↦ v) (l ↦ (v <|(codec.Pair.A') := A'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Pair_access_load_B l (v : (codec.Pair.t)) dq :
  AccessStrict
    (l.[(codec.Pair.t), "B"] ↦{dq} (v.(codec.Pair.B')))
    (l.[(codec.Pair.t), "B"] ↦{dq} (v.(codec.Pair.B')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Pair_access_store_B l (v : (codec.Pair.t)) B' :
  AccessStrict
    (l.[(codec.Pair.t), "B"] ↦ (v.(codec.Pair.B')))
    (l.[(codec.Pair.t), "B"] ↦ B')
    (l ↦ v) (l ↦ (v <|(codec.Pair.B') := B'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Pair.

End codec.
