(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.github_com.iasakura.perennial_sandbox.dll.

Set Default Proof Using "Type".

Module dll.
Module Node.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : dll.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Node_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (dll.Node.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "val" ∷ l.[(dll.Node.t), "val"] ↦{dq} v.(dll.Node.val') ∗
      "next" ∷ l.[(dll.Node.t), "next"] ↦{dq} v.(dll.Node.next') ∗
      "prev" ∷ l.[(dll.Node.t), "prev"] ↦{dq} v.(dll.Node.prev') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Node_into_val_typed
   :
  IntoValTypedUnderlying (dll.Node.t) (dll.Nodeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Node_access_load_val l (v : (dll.Node.t)) dq :
  AccessStrict
    (l.[(dll.Node.t), "val"] ↦{dq} (v.(dll.Node.val')))
    (l.[(dll.Node.t), "val"] ↦{dq} (v.(dll.Node.val')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Node_access_store_val l (v : (dll.Node.t)) val' :
  AccessStrict
    (l.[(dll.Node.t), "val"] ↦ (v.(dll.Node.val')))
    (l.[(dll.Node.t), "val"] ↦ val')
    (l ↦ v) (l ↦ (v <|(dll.Node.val') := val'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Node_access_load_next l (v : (dll.Node.t)) dq :
  AccessStrict
    (l.[(dll.Node.t), "next"] ↦{dq} (v.(dll.Node.next')))
    (l.[(dll.Node.t), "next"] ↦{dq} (v.(dll.Node.next')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Node_access_store_next l (v : (dll.Node.t)) next' :
  AccessStrict
    (l.[(dll.Node.t), "next"] ↦ (v.(dll.Node.next')))
    (l.[(dll.Node.t), "next"] ↦ next')
    (l ↦ v) (l ↦ (v <|(dll.Node.next') := next'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Node_access_load_prev l (v : (dll.Node.t)) dq :
  AccessStrict
    (l.[(dll.Node.t), "prev"] ↦{dq} (v.(dll.Node.prev')))
    (l.[(dll.Node.t), "prev"] ↦{dq} (v.(dll.Node.prev')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Node_access_store_prev l (v : (dll.Node.t)) prev' :
  AccessStrict
    (l.[(dll.Node.t), "prev"] ↦ (v.(dll.Node.prev')))
    (l.[(dll.Node.t), "prev"] ↦ prev')
    (l ↦ v) (l ↦ (v <|(dll.Node.prev') := prev'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Node.

Module List.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : dll.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance List_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (dll.List.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "head" ∷ l.[(dll.List.t), "head"] ↦{dq} v.(dll.List.head') ∗
      "tail" ∷ l.[(dll.List.t), "tail"] ↦{dq} v.(dll.List.tail') ∗
      "size" ∷ l.[(dll.List.t), "size"] ↦{dq} v.(dll.List.size') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance List_into_val_typed
   :
  IntoValTypedUnderlying (dll.List.t) (dll.Listⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance List_access_load_head l (v : (dll.List.t)) dq :
  AccessStrict
    (l.[(dll.List.t), "head"] ↦{dq} (v.(dll.List.head')))
    (l.[(dll.List.t), "head"] ↦{dq} (v.(dll.List.head')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance List_access_store_head l (v : (dll.List.t)) head' :
  AccessStrict
    (l.[(dll.List.t), "head"] ↦ (v.(dll.List.head')))
    (l.[(dll.List.t), "head"] ↦ head')
    (l ↦ v) (l ↦ (v <|(dll.List.head') := head'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance List_access_load_tail l (v : (dll.List.t)) dq :
  AccessStrict
    (l.[(dll.List.t), "tail"] ↦{dq} (v.(dll.List.tail')))
    (l.[(dll.List.t), "tail"] ↦{dq} (v.(dll.List.tail')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance List_access_store_tail l (v : (dll.List.t)) tail' :
  AccessStrict
    (l.[(dll.List.t), "tail"] ↦ (v.(dll.List.tail')))
    (l.[(dll.List.t), "tail"] ↦ tail')
    (l ↦ v) (l ↦ (v <|(dll.List.tail') := tail'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance List_access_load_size l (v : (dll.List.t)) dq :
  AccessStrict
    (l.[(dll.List.t), "size"] ↦{dq} (v.(dll.List.size')))
    (l.[(dll.List.t), "size"] ↦{dq} (v.(dll.List.size')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance List_access_store_size l (v : (dll.List.t)) size' :
  AccessStrict
    (l.[(dll.List.t), "size"] ↦ (v.(dll.List.size')))
    (l.[(dll.List.t), "size"] ↦ size')
    (l ↦ v) (l ↦ (v <|(dll.List.size') := size'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End List.

End dll.
