(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.github_com.iasakura.perennial_sandbox.example.

Set Default Proof Using "Type".

Module example.
Module Counter.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : example.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Counter_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (example.Counter.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "n" ∷ l.[(example.Counter.t), "n"] ↦{dq} v.(example.Counter.n') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Counter_into_val_typed
   :
  IntoValTypedUnderlying (example.Counter.t) (example.Counterⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Counter_access_load_n l (v : (example.Counter.t)) dq :
  AccessStrict
    (l.[(example.Counter.t), "n"] ↦{dq} (v.(example.Counter.n')))
    (l.[(example.Counter.t), "n"] ↦{dq} (v.(example.Counter.n')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Counter_access_store_n l (v : (example.Counter.t)) n' :
  AccessStrict
    (l.[(example.Counter.t), "n"] ↦ (v.(example.Counter.n')))
    (l.[(example.Counter.t), "n"] ↦ n')
    (l ↦ v) (l ↦ (v <|(example.Counter.n') := n'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Counter.

End example.
