(* autogenerated from github.com/iasakura/perennial-sandbox/codec *)
Require Export New.code.github_com.tchajed.marshal.
From New.golang Require Import defn.
Module pkg_id.
Definition codec : go_string := "github.com/iasakura/perennial-sandbox/codec".

End pkg_id.
Export pkg_id.
Module codec.

Definition Pair {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/iasakura/perennial-sandbox/codec.Pair"%go [].

#[global] Opaque Pair.

Definition Encode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/iasakura/perennial-sandbox/codec.Encode"%go.

Definition Decode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/iasakura/perennial-sandbox/codec.Decode"%go.

(* Encode serializes p as A then B, little-endian, into a fresh byte slice.

   go: codec.go:15:6 *)
Definition Encodeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "p",
    exception_do (let: "p" := (GoAlloc Pair "p") in
    let: "b" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: "$r0" := (let: "$a0" := (![go.SliceType go.byte] "b") in
    let: "$a1" := (![go.uint64] (StructFieldRef Pair "A"%go "p")) in
    (FuncResolve marshal.WriteInt [] #()) "$a0" "$a1") in
    do:  ("b" <-[go.SliceType go.byte] "$r0");;;
    let: "$r0" := (let: "$a0" := (![go.SliceType go.byte] "b") in
    let: "$a1" := (![go.uint64] (StructFieldRef Pair "B"%go "p")) in
    (FuncResolve marshal.WriteInt [] #()) "$a0" "$a1") in
    do:  ("b" <-[go.SliceType go.byte] "$r0");;;
    return: (![go.SliceType go.byte] "b")).

(* Decode parses a Pair back out of b (assuming b starts with the encoding).

   go: codec.go:23:6 *)
Definition Decodeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "b",
    exception_do (let: "b" := (GoAlloc (go.SliceType go.byte) "b") in
    let: "b2" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: "a" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![go.SliceType go.byte] "b") in
    (FuncResolve marshal.ReadInt [] #()) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("a" <-[go.uint64] "$r0");;;
    do:  ("b2" <-[go.SliceType go.byte] "$r1");;;
    let: "c" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := (![go.SliceType go.byte] "b2") in
    (FuncResolve marshal.ReadInt [] #()) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("c" <-[go.uint64] "$r0");;;
    do:  "$r1";;;
    return: (let: "$v0" := (![go.uint64] "a") in
     let: "$v1" := (![go.uint64] "c") in
     CompositeLiteral Pair (LiteralValue [KeyedElement (Some (KeyField "A"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "B"%go)) (ElementExpression go.uint64 "$v1")]))).

#[global] Instance info' : PkgInfo pkg_id.codec :=
{|
  pkg_imported_pkgs := [code.github_com.tchajed.marshal.pkg_id.marshal]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.codec (λ: <>,
      exception_do (do:  (marshal.initialize' #()))
      ).

Module Pair.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  A' : w64;
  B' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Pair.

Definition Pair'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "A"%go go.uint64);
  (go.FieldDecl "B"%go go.uint64)
].
Program Definition Pair'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Pair'fds_unsealed).
Global Instance equals_unfold_Pair {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Pair'fds =→ Pair'fds_unsealed.
Proof. rewrite /Pair'fds seal_eq //. Qed.

Definition Pairⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Pair'fds).

Class Pair_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Pair_type_repr  :: go.TypeReprUnderlying Pairⁱᵐᵖˡ Pair.t;
  #[global] Pair_underlying :: (Pair) <u (Pairⁱᵐᵖˡ);
  #[global] Pair_get_A (x : Pair.t) :: ⟦StructFieldGet (Pairⁱᵐᵖˡ) "A", #x⟧ ⤳[under] #x.(Pair.A');
  #[global] Pair_set_A (x : Pair.t) y :: ⟦StructFieldSet (Pairⁱᵐᵖˡ) "A", (#x, #y)⟧ ⤳[under] #(x <|Pair.A' := y|>);
  #[global] Pair_get_B (x : Pair.t) :: ⟦StructFieldGet (Pairⁱᵐᵖˡ) "B", #x⟧ ⤳[under] #x.(Pair.B');
  #[global] Pair_set_B (x : Pair.t) y :: ⟦StructFieldSet (Pairⁱᵐᵖˡ) "B", (#x, #y)⟧ ⤳[under] #(x <|Pair.B' := y|>);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Pair_instance :: Pair_Assumptions;
  #[global] Encode_unfold :: FuncUnfold Encode [] (Encodeⁱᵐᵖˡ);
  #[global] Decode_unfold :: FuncUnfold Decode [] (Decodeⁱᵐᵖˡ);
  #[global] import_marshal_Assumption :: marshal.Assumptions;
}.
End codec.
