(* autogenerated from github.com/iasakura/perennial-sandbox/dll *)
From New.golang Require Import defn.
Module pkg_id.
Definition dll : go_string := "github.com/iasakura/perennial-sandbox/dll".

End pkg_id.
Export pkg_id.
Module dll.

Definition Node {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/iasakura/perennial-sandbox/dll.Node"%go [].

#[global] Opaque Node.

Definition List {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/iasakura/perennial-sandbox/dll.List"%go [].

#[global] Opaque List.

Definition NewList {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/iasakura/perennial-sandbox/dll.NewList"%go.

(* NewList returns an empty list.

   go: list.go:20:6 *)
Definition NewListⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: (GoAlloc List (let: "$v0" := UntypedNil in
     let: "$v1" := UntypedNil in
     let: "$v2" := #(W64 0) in
     CompositeLiteral List (LiteralValue [KeyedElement (Some (KeyField "head"%go)) (ElementExpression go.untyped_nil "$v0"); KeyedElement (Some (KeyField "tail"%go)) (ElementExpression go.untyped_nil "$v1"); KeyedElement (Some (KeyField "size"%go)) (ElementExpression go.uint64 "$v2")])))).

(* PushBack appends v at the tail.

   go: list.go:25:16 *)
Definition List__PushBackⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" "v",
    exception_do (let: "l" := (GoAlloc (go.PointerType List) "l") in
    let: "v" := (GoAlloc go.uint64 "v") in
    let: "n" := (GoAlloc (go.PointerType Node) (GoZeroVal (go.PointerType Node) #())) in
    let: "$r0" := (GoAlloc Node (let: "$v0" := (![go.uint64] "v") in
    let: "$v1" := UntypedNil in
    let: "$v2" := (![go.PointerType Node] (StructFieldRef List "tail"%go (![go.PointerType List] "l"))) in
    CompositeLiteral Node (LiteralValue [KeyedElement (Some (KeyField "val"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "next"%go)) (ElementExpression go.untyped_nil "$v1"); KeyedElement (Some (KeyField "prev"%go)) (ElementExpression (go.PointerType Node) "$v2")]))) in
    do:  ("n" <-[go.PointerType Node] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.PointerType Node] (StructFieldRef List "tail"%go (![go.PointerType List] "l"))) =⟨go.PointerType Node⟩ (Convert go.untyped_nil (go.PointerType Node) UntypedNil))
    then
      let: "$r0" := (![go.PointerType Node] "n") in
      do:  ((StructFieldRef List "head"%go (![go.PointerType List] "l")) <-[go.PointerType Node] "$r0")
    else
      let: "$r0" := (![go.PointerType Node] "n") in
      do:  ((StructFieldRef Node "next"%go (![go.PointerType Node] (StructFieldRef List "tail"%go (![go.PointerType List] "l")))) <-[go.PointerType Node] "$r0"));;;
    let: "$r0" := (![go.PointerType Node] "n") in
    do:  ((StructFieldRef List "tail"%go (![go.PointerType List] "l")) <-[go.PointerType Node] "$r0");;;
    let: "$r0" := ((![go.uint64] (StructFieldRef List "size"%go (![go.PointerType List] "l"))) +⟨go.uint64⟩ #(W64 1)) in
    do:  ((StructFieldRef List "size"%go (![go.PointerType List] "l")) <-[go.uint64] "$r0");;;
    return: #()).

(* PushFront prepends v at the head.

   go: list.go:37:16 *)
Definition List__PushFrontⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" "v",
    exception_do (let: "l" := (GoAlloc (go.PointerType List) "l") in
    let: "v" := (GoAlloc go.uint64 "v") in
    let: "n" := (GoAlloc (go.PointerType Node) (GoZeroVal (go.PointerType Node) #())) in
    let: "$r0" := (GoAlloc Node (let: "$v0" := (![go.uint64] "v") in
    let: "$v1" := (![go.PointerType Node] (StructFieldRef List "head"%go (![go.PointerType List] "l"))) in
    let: "$v2" := UntypedNil in
    CompositeLiteral Node (LiteralValue [KeyedElement (Some (KeyField "val"%go)) (ElementExpression go.uint64 "$v0"); KeyedElement (Some (KeyField "next"%go)) (ElementExpression (go.PointerType Node) "$v1"); KeyedElement (Some (KeyField "prev"%go)) (ElementExpression go.untyped_nil "$v2")]))) in
    do:  ("n" <-[go.PointerType Node] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.PointerType Node] (StructFieldRef List "head"%go (![go.PointerType List] "l"))) =⟨go.PointerType Node⟩ (Convert go.untyped_nil (go.PointerType Node) UntypedNil))
    then
      let: "$r0" := (![go.PointerType Node] "n") in
      do:  ((StructFieldRef List "tail"%go (![go.PointerType List] "l")) <-[go.PointerType Node] "$r0")
    else
      let: "$r0" := (![go.PointerType Node] "n") in
      do:  ((StructFieldRef Node "prev"%go (![go.PointerType Node] (StructFieldRef List "head"%go (![go.PointerType List] "l")))) <-[go.PointerType Node] "$r0"));;;
    let: "$r0" := (![go.PointerType Node] "n") in
    do:  ((StructFieldRef List "head"%go (![go.PointerType List] "l")) <-[go.PointerType Node] "$r0");;;
    let: "$r0" := ((![go.uint64] (StructFieldRef List "size"%go (![go.PointerType List] "l"))) +⟨go.uint64⟩ #(W64 1)) in
    do:  ((StructFieldRef List "size"%go (![go.PointerType List] "l")) <-[go.uint64] "$r0");;;
    return: #()).

(* Len returns the number of elements.

   go: list.go:49:16 *)
Definition List__Lenⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "l" <>,
    exception_do (let: "l" := (GoAlloc (go.PointerType List) "l") in
    return: (![go.uint64] (StructFieldRef List "size"%go (![go.PointerType List] "l")))).

#[global] Instance info' : PkgInfo pkg_id.dll :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.dll (λ: <>,
      exception_do (do:  #())
      ).

Module Node.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  val' : w64;
  next' : loc;
  prev' : loc;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Node.

Definition Node'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "val"%go go.uint64);
  (go.FieldDecl "next"%go (go.PointerType Node));
  (go.FieldDecl "prev"%go (go.PointerType Node))
].
Program Definition Node'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Node'fds_unsealed).
Global Instance equals_unfold_Node {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Node'fds =→ Node'fds_unsealed.
Proof. rewrite /Node'fds seal_eq //. Qed.

Definition Nodeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Node'fds).

Class Node_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Node_type_repr  :: go.TypeReprUnderlying Nodeⁱᵐᵖˡ Node.t;
  #[global] Node_underlying :: (Node) <u (Nodeⁱᵐᵖˡ);
  #[global] Node_get_val (x : Node.t) :: ⟦StructFieldGet (Nodeⁱᵐᵖˡ) "val", #x⟧ ⤳[under] #x.(Node.val');
  #[global] Node_set_val (x : Node.t) y :: ⟦StructFieldSet (Nodeⁱᵐᵖˡ) "val", (#x, #y)⟧ ⤳[under] #(x <|Node.val' := y|>);
  #[global] Node_get_next (x : Node.t) :: ⟦StructFieldGet (Nodeⁱᵐᵖˡ) "next", #x⟧ ⤳[under] #x.(Node.next');
  #[global] Node_set_next (x : Node.t) y :: ⟦StructFieldSet (Nodeⁱᵐᵖˡ) "next", (#x, #y)⟧ ⤳[under] #(x <|Node.next' := y|>);
  #[global] Node_get_prev (x : Node.t) :: ⟦StructFieldGet (Nodeⁱᵐᵖˡ) "prev", #x⟧ ⤳[under] #x.(Node.prev');
  #[global] Node_set_prev (x : Node.t) y :: ⟦StructFieldSet (Nodeⁱᵐᵖˡ) "prev", (#x, #y)⟧ ⤳[under] #(x <|Node.prev' := y|>);
}.

Module List.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  head' : loc;
  tail' : loc;
  size' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End List.

Definition List'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "head"%go (go.PointerType Node));
  (go.FieldDecl "tail"%go (go.PointerType Node));
  (go.FieldDecl "size"%go go.uint64)
].
Program Definition List'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (List'fds_unsealed).
Global Instance equals_unfold_List {ext : ffi_syntax} {go_gctx : GoGlobalContext} : List'fds =→ List'fds_unsealed.
Proof. rewrite /List'fds seal_eq //. Qed.

Definition Listⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (List'fds).

Class List_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] List_type_repr  :: go.TypeReprUnderlying Listⁱᵐᵖˡ List.t;
  #[global] List_underlying :: (List) <u (Listⁱᵐᵖˡ);
  #[global] List_get_head (x : List.t) :: ⟦StructFieldGet (Listⁱᵐᵖˡ) "head", #x⟧ ⤳[under] #x.(List.head');
  #[global] List_set_head (x : List.t) y :: ⟦StructFieldSet (Listⁱᵐᵖˡ) "head", (#x, #y)⟧ ⤳[under] #(x <|List.head' := y|>);
  #[global] List_get_tail (x : List.t) :: ⟦StructFieldGet (Listⁱᵐᵖˡ) "tail", #x⟧ ⤳[under] #x.(List.tail');
  #[global] List_set_tail (x : List.t) y :: ⟦StructFieldSet (Listⁱᵐᵖˡ) "tail", (#x, #y)⟧ ⤳[under] #(x <|List.tail' := y|>);
  #[global] List_get_size (x : List.t) :: ⟦StructFieldGet (Listⁱᵐᵖˡ) "size", #x⟧ ⤳[under] #x.(List.size');
  #[global] List_set_size (x : List.t) y :: ⟦StructFieldSet (Listⁱᵐᵖˡ) "size", (#x, #y)⟧ ⤳[under] #(x <|List.size' := y|>);
  #[global] List'ptr_Len_unfold :: MethodUnfold (go.PointerType (List)) "Len" (List__Lenⁱᵐᵖˡ);
  #[global] List'ptr_PushBack_unfold :: MethodUnfold (go.PointerType (List)) "PushBack" (List__PushBackⁱᵐᵖˡ);
  #[global] List'ptr_PushFront_unfold :: MethodUnfold (go.PointerType (List)) "PushFront" (List__PushFrontⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Node_instance :: Node_Assumptions;
  #[global] List_instance :: List_Assumptions;
  #[global] NewList_unfold :: FuncUnfold NewList [] (NewListⁱᵐᵖˡ);
}.
End dll.
