(* autogenerated from github.com/iasakura/perennial-sandbox/example *)
From New.golang Require Import defn.
Module pkg_id.
Definition example : go_string := "github.com/iasakura/perennial-sandbox/example".

End pkg_id.
Export pkg_id.
Module example.

Definition Counter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/iasakura/perennial-sandbox/example.Counter"%go [].

#[global] Opaque Counter.

Definition MaxRetries {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 3).

Definition Add {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/iasakura/perennial-sandbox/example.Add"%go.

Definition SumTo {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/iasakura/perennial-sandbox/example.SumTo"%go.

(* Add returns the sum of two machine integers.

   go: example.go:9:6 *)
Definition Addⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "a" "b",
    exception_do (let: "b" := (GoAlloc go.uint64 "b") in
    let: "a" := (GoAlloc go.uint64 "a") in
    return: ((![go.uint64] "a") +⟨go.uint64⟩ (![go.uint64] "b"))).

(* Inc bumps the counter by one.

   go: example.go:19:19 *)
Definition Counter__Incⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "c" <>,
    exception_do (let: "c" := (GoAlloc (go.PointerType Counter) "c") in
    let: "$r0" := ((![go.uint64] (StructFieldRef Counter "n"%go (![go.PointerType Counter] "c"))) +⟨go.uint64⟩ #(W64 1)) in
    do:  ((StructFieldRef Counter "n"%go (![go.PointerType Counter] "c")) <-[go.uint64] "$r0");;;
    return: #()).

(* Get reads the current value.

   go: example.go:24:19 *)
Definition Counter__Getⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "c" <>,
    exception_do (let: "c" := (GoAlloc (go.PointerType Counter) "c") in
    return: (![go.uint64] (StructFieldRef Counter "n"%go (![go.PointerType Counter] "c")))).

(* SumTo computes 0 + 1 + ... + (n-1) using goose's canonical `for cond {}` loop.

   go: example.go:29:6 *)
Definition SumToⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "n",
    exception_do (let: "n" := (GoAlloc go.uint64 "n") in
    let: "total" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := #(W64 0) in
    do:  ("total" <-[go.uint64] "$r0");;;
    let: "i" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "$r0" := #(W64 0) in
    do:  ("i" <-[go.uint64] "$r0");;;
    (for: (λ: <>, (![go.uint64] "i") <⟨go.uint64⟩ (![go.uint64] "n")); (λ: <>, #()) := λ: <>,
      let: "$r0" := ((![go.uint64] "total") +⟨go.uint64⟩ (![go.uint64] "i")) in
      do:  ("total" <-[go.uint64] "$r0");;;
      let: "$r0" := ((![go.uint64] "i") +⟨go.uint64⟩ #(W64 1)) in
      do:  ("i" <-[go.uint64] "$r0"));;;
    return: (![go.uint64] "total")).

#[global] Instance info' : PkgInfo pkg_id.example :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.example (λ: <>,
      exception_do (do:  #())
      ).

Module Counter.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  n' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Counter.

Definition Counter'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "n"%go go.uint64)
].
Program Definition Counter'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Counter'fds_unsealed).
Global Instance equals_unfold_Counter {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Counter'fds =→ Counter'fds_unsealed.
Proof. rewrite /Counter'fds seal_eq //. Qed.

Definition Counterⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Counter'fds).

Class Counter_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Counter_type_repr  :: go.TypeReprUnderlying Counterⁱᵐᵖˡ Counter.t;
  #[global] Counter_underlying :: (Counter) <u (Counterⁱᵐᵖˡ);
  #[global] Counter_get_n (x : Counter.t) :: ⟦StructFieldGet (Counterⁱᵐᵖˡ) "n", #x⟧ ⤳[under] #x.(Counter.n');
  #[global] Counter_set_n (x : Counter.t) y :: ⟦StructFieldSet (Counterⁱᵐᵖˡ) "n", (#x, #y)⟧ ⤳[under] #(x <|Counter.n' := y|>);
  #[global] Counter'ptr_Get_unfold :: MethodUnfold (go.PointerType (Counter)) "Get" (Counter__Getⁱᵐᵖˡ);
  #[global] Counter'ptr_Inc_unfold :: MethodUnfold (go.PointerType (Counter)) "Inc" (Counter__Incⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Counter_instance :: Counter_Assumptions;
  #[global] Add_unfold :: FuncUnfold Add [] (Addⁱᵐᵖˡ);
  #[global] SumTo_unfold :: FuncUnfold SumTo [] (SumToⁱᵐᵖˡ);
}.
End example.
